<?php
G::LoadClass("plugin");

class custom_apiPlugin extends PMPlugin
{
  
  
  public function custom_apiPlugin($sNamespace, $sFilename = null)
  {
    $res = parent::PMPlugin($sNamespace, $sFilename);
    $this->sFriendlyName = "custom_api Plugin";
    $this->sDescription  = "Autogenerated plugin for class custom_api";
    $this->sPluginFolder = "custom_api";
    $this->sSetupPage    = "setup";
    $this->iVersion      = 1;
    //$this->iPMVersion    = 2425;
    $this->aWorkspaces   = null;
    //$this->aWorkspaces = array("os");
    $this->enableRestService(true);
    
    
    
    return $res;
  }

  public function setup()
  {
    
    
  }

  public function install()
  {
  }
  
  public function enable()
  {
    
  }

  public function disable()
  {
    
  }
  
}

$oPluginRegistry = &PMPluginRegistry::getSingleton();
$oPluginRegistry->registerPlugin("custom_api", __FILE__);
